### ISSUE TITLE
firebase registraion database uid issue

### ISSUE THREAD

**Issue by RizwanSaeedi** [planetoftheweb/angularregistration#10]
When i register , i got this database error. in authentcaion user added, but not in db

Reference.child failed: First argument was an invalid path = "undefined". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"

**Comment by gaborvrg** [comment]
in the section of myObject.register,

**`register: function(user){
                auth.$createUserWithEmailAndPassword(
                    user.email,
                    user.password
                ).then(function(regUser) {`**

 you should change these from
**`ref.child('users').child(regUser.uid).set({`
`regUser: regUser.uid,`**

to
**`ref.child('users').child(regUser.user.uid).set({`
`regUser: regUser.user.uid,`**

It works for me.

**Comment by RizwanSaeedi** [comment]
Thanks You so much . I am very happy now that i got solution.
